import {StyleSheet} from 'react-native';
export const modalStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ModalBody: {
    width: '97%',
    paddingVertical: 20,
    backgroundColor: '#222222',
    borderRadius: 20,
    height: 580,
  },
  Send_Recieve_SwitchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 20,
  },
  Send_Recieve_SwitchButton: {justifyContent: 'center', alignItems: 'center'},
  Send_Recieve_SwitchText: {
    textAlign: 'center',
    fontSize: 22,
  },
  AmmountEntryContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginTop: 20,
    elevation: 3,
    zIndex: 999,
  },
  CurrencySwapContainer: {
    justifyContent: 'space-evenly',
    paddingVertical: 10,
  },
  CurrencyName: {
    fontSize: 18,
    color: '#B8B8B8',
    textAlign: 'center',
    textAlignVertical: 'center',
    paddingVertical: 2,
    paddingHorizontal: 5,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: '#5a5a5a',
  },
  CurrencyInputContainer: {
    marginVertical: 20,
    width: '40%',
  },
  CurrencyInputTextContainer: {
    borderBottomWidth: 0,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  CurrencyInput: {
    fontSize: 48,
    color: '#5a5a5a',
    paddingBottom: 0,
    paddingTop: 0,
  },
  InputLeftIcon: {
    justifyContent: 'flex-end',
  },
  InputContainer: {marginTop: 20, paddingHorizontal: 20},
  InputLHSText: {
    fontSize: 18,
    color: 'white',
    textAlign: 'center',
    marginRight: 30,
  },
  ContainerStyle: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  Input: {
    fontSize: 16,
    paddingBottom: 0,
    paddingLeft: 0,
    color: '#5a5a5a',
  },
  WordsLeftText: {color: '#5a5a5a', alignSelf: 'flex-end'},
  PaymentMethodContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  PayWithText: {
    fontSize: 18,
    color: 'white',
    textAlign: 'center',
    marginRight: 35,
  },
  DropDownPanel: {
    width: 130,
  },
  DropDownContainer: {
    borderRadius: 15,
    elevation: 5,
    paddingVertical: 10,
    backgroundColor: '#222222',
    marginVertical: 5,
    borderWidth: 2,
    borderColor: 'black',
    color: 'white',
  },
  DropDownPlaceholder: {
    fontSize: 18,
    color: '#5a5a5a',
    marginLeft: 5,
  },
  DropDownList: {
    borderBottomWidth: 1,
    borderColor: 'grey',
    marginHorizontal: '5%',
    padding: 10,
  },
  BottomContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 5,
    marginTop: 20,
  },
  Back: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
  },
  Continue: {
    backgroundColor: '#0076FF',
    justifyContent: 'center',
    paddingVertical: 10,
    width: 100,
    borderRadius: 7,
  },
  ButtonText: {
    textAlign: 'center',
    fontSize: 16,
    color: 'white',
    fontWeight: 'bold',
  },
  AssetsSelection: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 30,
    marginTop: 20,
    elevation: 5,
    backgroundColor: '#222222',
  },
  AssetAddressContainer: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: '#222222',
  },
  AssetAddressText: {
    fontSize: 18,
    color: 'white',
    textAlign: 'center',
  },
  AssetCopyText: {
    fontSize: 18,
    color: '#717171',
    textAlign: 'center',
    marginHorizontal: 10,
  },
  AssetKey: {
    fontSize: 18,
    color: '#5a5a5a',
  },
});
